# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - webapp-201123195549-hello

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Java version
      uses: actions/setup-java@v1
      with:
        java-version: '8'

    - name: Build with Maven
      run: mvn clean install

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'webapp-201123195549-hello'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_91b9d49d53a74d3eb2bbaa1d32fedb89 }}
        package: '${{ github.workspace }}/target/*.jar'